### ISSUE TITLE
accessing parameters in ruby

### ISSUE THREAD

**Issue by pickledrick** [envato/stack_master#143]
Hi Guys,

Thanks for the Gem!

Is there a way I can access a parameter in ruby rather than use a parsed parameter in cfndsl.

For example I want to do something like

Description parameters['environment'] + 'ec2_cloudformation_stack'

Rather than an FnJoin with a Cloudformation parameter

Thanks for your help,

thebeefcake.

**Comment by patrobinson** [comment]
Short answer:

Not currently

Long answer:

You cannot dereference parameters before the template is compiled by CloudFormation. DSLs like cfndsl provide a wrapper, but ultimately just compile a JSON template that's submitted to the CloudFormation API. Since StackMaster uses CloudFormation parameters, the value of that parameter is not looked up at any level until it's submitted to the API. So your DSL (whether it be Sparkleformation or cfndsl) has no capability to know the parameter value at (it's) compile time.

It might be possible to submit the parameters to cfndsl or SparkleFormation as a variable or method for dereferencing, so that it can know about them, but this functionality does not exist today.

**Comment by thebeefcake** [comment]
Thanks Patrick,

I'm not sure I was clear in what I was trying to do, Is there a way to use a parameter defined in yaml as a variable in ruby/cfndsl rather than bringing it in as a cloudformation parameter.

**Comment by patrobinson** [comment]
The parameters are available to stack master and Cloudformation but not the DSL (and hence no code written in the DSL) without calling out to StackMaster, and exposing a lot of implementation details to the DSL. This would be extremely fragile and likely to break with updates to StackMaster.

The only way I can see to do this would to change StackMaster to pass the parameters to the DSL library when we compile the template. This seems possible with Cfndsl.

**Comment by redterror** [comment]
I started on addressing this in #120 but it still needs a little more work.

**Comment by elmobp** [comment]
@redterror see #144 its complete in there

**Comment by patrobinson** [comment]
Implemented in #120 and released in 1.10
