### ISSUE TITLE
Add ability for 'UsePreviousValue' option when defining parameters.

### ISSUE THREAD

**Issue by WhileLoop** [envato/stack_master#171]
I would like to be able to use the previous values of certain parameters when applying updates. Perhaps parameters which are not defined or are left blank could default to use the previous value if it is present in the stack already. Another option is to have some way to explicitly use previous values.

**Comment by patrobinson** [comment]
Is this in the context of using a Parameter Resolver? Can you give a little more context about the use case for this?

I see anything that relies on what's in CloudFormation (parameters or otherwise) as a bit of an anti-pattern. The source of truth should primarily be the repository where the StackMaster config lives, except for Parameter Resolvers where the source of truth is some API call. In the case of the repository a roll back would be a simple git revert/commit, with the API call to say use an AMI then tags can be used to control the release/yank of an artefact.
