### ISSUE TITLE
stack_master validate should validate parameters

### ISSUE THREAD

**Issue by arecker** [envato/stack_master#189]
Is there any interest in making `stack_master validate` validate parameters as well as the template?

`stack_master validate` is convenient to run in a build, but it doesn't check parameter files.  In many cases, we have a valid template, but we forget a few parameters.  The build will pass, but we'll get an error that looks like this when we attempt to apply.

```
Empty/blank parameters detected, ensure values exist for those parameters. Parameters will be read from the following locations: ...
```

Currently, the only way to validate the parameters is with `apply`.  We tried using `apply --no` as a workaround, but since `apply` changes the state of a stack, sometimes it will leave things in a weird state (like REVIEW_IN_PROGRESS).

Could we either make `validate` check that all the parameters exist, or at least acknowledge a `--parameters` flag for this extra behavior?

**Comment by patrobinson** [comment]
The validation you're seeing with `apply --no` is done by CloudFormation, the reason it goes into the state `REVIEW_IN_PROGRESS` is because StackMaster submits a change set to CF in order to perform that validation. Currently the validate command simply calls the CloudFormation ValidateTemplate API action.

So I think the only way to do this is to implement our own parameter validation.

**Comment by arecker** [comment]
> So I think the only way to do this is to implement our own parameter
> validation.

This seems doable.  I remember seeing at least one place where the code
was opening up the compiled template to see if any parameters were
missing.  I'd be happy to work on this while the ticket is open.
