### ISSUE TITLE
Secret integration for AWS parameter store

### ISSUE THREAD

**Issue by jacobbednarz** [envato/stack_master#197]
Up until now, `dotgpg` has served us well and allowed us to restrict who
has access to what secrets within our stacks. However, we now have a
need to do more automation with our cloudformation stacks and we aren't
fully comfortable giving non-humans GPG access. 

To address this, I've considered adding a new parameter resolver that
uses AWS parameter store and permission off access via a new IAM policy
that would restrict what secrets the service would have access to. This
would also allow us to move all the secrets into parameter store and
allow/deny access to individual secrets instead of our current all or
nothing approach some services have.

Is this something others would be interested in?

**Comment by stevehodgkiss** [comment]
+1, although I'd be more interested in a secret store that uses KMS to encrypt a secret file (similar to the GPG one) over Parameter Store. I'd prefer that because changes to parameters would be kept in source control. Although you can view a given parameters changes in ParameterStore, a parameter can't be retrieved after it's deleted.

**Comment by jacobbednarz** [comment]
@stevehodgkiss so in your mind a file with a `key:value` pair encrypted with KMS would be a better idea? Is this how you'd envision the workflow?
 
- Developer assumes role with correct KMS permissions
- Decrypts local copy of file
- Adds/Updates file
- Recrypts file
- Commit to version control 

I don't mind the concept however I would be slightly concerned about people forgetting to recrypt with KMS being committing back to the repository. `dotgpg` prevents this because you need to use `dotgpg edit <file>` and it handles encryption on exit.

**Comment by andrewjhumphrey** [comment]
Sorry, just noticed this issue. I should have perhaps got involved here before I did my parameter store resolver.   Check out release 1.2.0 @jacobbednarz it might be sufficient for your needs.

The biggest problem with using IAM as fine grained arbiter (via KMS  key policies)  of who gets access to which parameter is the case where a common role is used by folks when manipulating stacks rather than individual accounts...
