### ISSUE TITLE
General Inquiry on Directory Structure

### ISSUE THREAD

**Issue by TheCrimsinGhost** [envato/stack_master#320]
Just wondering if there is a way to reference custom template/parameter locations within the stack_master.yaml?
I am separating good sized deployment into directories based on services and applications and would like to control it all in 1 stack_master file.

Example:

Stack_master.yaml Structure:
stacks:
    us-west-2:
        rds:
            template: rds/template/rds.yaml
            parameters: rds/parameters/rds.yaml
        ec2:
            template: ec2/template/ec2.yaml
            parameters: ec2/parameters/ec2.yaml

Directory Structure:
stack_master.yaml
    rds/
        templates/
            rds.yaml
        parameters/
            rds.yaml
    ec2/
        templates/
            ec2.yaml
        parameters/
            ec2.yaml

**Comment by patrobinson** [comment]
Hi @TheCrimsinGhost 

You can use [template_dir](https://github.com/envato/stack_master#compiler-options--alternate-template-directories) to specify the location of templates.

You cannot specify a different parameter directory, it must be located in the same directory as the `stack_master.yml` file. You can, however, abuse `region_aliases` for this purpose. Since StackMaster will look for configuration files in `parameters/<region_alias>/<stack_name>.yml`, it's possible to specify an aliases such as "appA" and "appB" and place their respective parameters in `parameters/appA` etc.

This might also provide a nice way to break up services in your stack_master.yml file.

**Comment by TheCrimsinGhost** [comment]
Cool, thank you sir

**Comment by TheCrimsinGhost** [comment]
so the template_dir is a single use at the root of the stack_master.yml?  not necessarily definable within each stack definition: 
ie..........
stacks:
    AppSvr:
      template: AppSvr.yaml
      template_dir: ./templates/Appsvr

**Comment by patrobinson** [comment]
@TheCrimsinGhost sorry yes. One `stack_master.yml` can only have one template directory.

**Comment by TheCrimsinGhost** [comment]
How much effort would it take to allow the template directory at the stack/template level?
ie..........
stacks:
  AppSvr:
    template: AppSvr.yaml
    template_dir: ./templates/Appsvr

**Comment by patrobinson** [comment]
@TheCrimsinGhost it shouldn't be too hard to allow that to over-ride the default.
We pass it in [here](https://github.com/envato/stack_master/blob/d3f96df0c2ee91a5b784bf49f012c814aa39997b/lib/stack_master/config.rb#L117) as a hard coded variable, but could just as easily pass something from `attributes`
